[package]
name = "abbrev"
version = "0.1.0"
authors = ["rdavidson <rdavidson@accusoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codepage-437 = "0.1.0"
